In [2]:
import numpy as np

# **1. Why NumPy? (Scientific Computing Foundation)**

In [3]:
import sys
py_list = list(range(1000))
np_array = np.arange(1000)

print(f"List memory: {sys.getsizeof(py_list)} bytes") 
print(f"NumPy memory: {np_array.nbytes} bytes")
#Like shipping containers vs loose cargo - NumPy's fixed-type arrays enable efficient vectorized operations.

List memory: 8056 bytes
NumPy memory: 4000 bytes


# **2. Array Creation & Attributes**

In [5]:

k = np.array([1,2,3,4,5,6])  # 1 d array
#print("Shape:", k.shape)     
#print("Dimensions:", k.ndim) 
#print("Data type:", k.dtype) # int64

Data type: int32


In [8]:
# Creation methods
a = np.array([[1, 2, 3], [4, 5, 6]])  # From list

print("Shape:", a.shape)     # (2, 3)
print("Dimensions:", a.ndim) # 2
print("Data type:", a.dtype) # int64

Shape: (2, 3)
Dimensions: 2
Data type: int32


In [9]:
b = np.zeros((2,3))      # Zeros matrix
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
c = np.linspace(0, 10, 5)   # Linear spaced values
print(c)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
d = np.random.randint(0, 100, (3,5))    # Random matrix
print(d)

[[97 52 92 12  6]
 [55 61 62 16 80]
 [30 31 20 20 12]]


# **Vectorization & Broadcasting**


In [14]:
# Element-wise operations (NO LOOPS!)
arr = np.array([[1, 2, 3], [4,3,6]])
squares = arr ** 2             
print(squares)

[[ 1  4  9]
 [16  9 36]]


In [15]:
a = np.array([1, 2, 3])

# Add scalar to array
result = a + 5
print(result)  # Output: [6 7 8]
#Explanation: 5 is broadcast to [5, 5, 5] internally.

[6 7 8]


In [16]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Vectorized addition
result = a + b
print(result)  


[11 22 33]


In [17]:
#Broadcasting works across dimensions.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

row = np.array([10, 20, 30])

# Broadcast row to each row of matrix
result = matrix + row
print(result)
#Explanation: The 1D row is "stretched" across each row of the matrix.


[[11 22 33]
 [14 25 36]]


In [18]:
col = np.array([[1],
                [2],
                [3]])  # 3*1
row = np.array([10, 20, 30])  # 1*3

result = col + row
print(result)
#Explanation: Column (3×1) and row (1×3) are broadcast into a (3×3) matrix.

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [19]:
#Element-wise Multiplication of Different Shapes
a = np.array([[1, 2, 3],
              [4, 5, 6]])

scaling_factors = np.array([1, 10, 100])  # shape (3,)

# Each column gets multiplied by its corresponding factor
result = a * scaling_factors
print(result)

[[  1  20 300]
 [  4  50 600]]


# **Mathematical Operations**

In [20]:
# Aggregations
data = np.random.normal(0, 1, 1000)  # Normal distribution
print(f"Mean: {data.mean():.2f}, STD: {data.std():.2f}")


Mean: -0.01, STD: 0.98


In [21]:
# Linear algebra
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = A @ B  # Matrix multiplication
determinant = np.linalg.det(A)
print(dot_product)
print(determinant)


[[19 22]
 [43 50]]
-2.0000000000000004


# **Real-world Applications**

Physics: Solving differential equations

In [4]:
# Heat diffusion model
x = np.linspace(0, 10, 100)
temperature = np.sin(x) * np.exp(-0.1*x)
print(temperature)

[ 0.          0.09982498  0.19663601  0.2895066   0.37756892  0.46002152
  0.53613617  0.60526378  0.66683948  0.72038667  0.7655201   0.80194802
  0.82947321  0.84799316  0.85749919  0.8580747   0.84989241  0.83321087
  0.8083701   0.77578648  0.73594698  0.6894028   0.63676244  0.57868439
  0.51586937  0.4490524   0.37899457  0.30647479  0.23228148  0.15720436
  0.08202636  0.00751578 -0.06558124 -0.13654791 -0.20470347 -0.26940944
 -0.33007527 -0.38616339 -0.43719365 -0.48274706 -0.52246884 -0.55607072
 -0.5833326  -0.6041034  -0.61830122 -0.6259128  -0.62699228 -0.62165929
 -0.61009643 -0.59254615 -0.5693071  -0.5407299  -0.50721262 -0.46919568
 -0.42715659 -0.38160427 -0.33307331 -0.28211794 -0.22930604 -0.17521305
 -0.12041595 -0.06548736 -0.0109898   0.04252986  0.09454566  0.14455749
  0.19209565  0.23672506  0.278049    0.31571235  0.34940443  0.37886124
  0.40386724  0.42425654  0.43991366  0.45077364  0.45682173  0.45809252
  0.45466859  0.44667874  0.43429572  0.41773361  0

Data Preprocessing

### comparing numpy operations with normal operations

In [6]:
import random
import time

# Create sample marks for 10000 students (5 subjects each)
students = [[random.randint(40, 100) for _ in range(5)] for _ in range(10000)]

start = time.perf_counter_ns()
# Compute total and average using loops
totals = []
averages = []
for student in students:
    total = sum(student)
    avg = total / len(student)
    totals.append(total)
    averages.append(avg)
    
end = time.perf_counter_ns()
print("Time taken (Python list):", round(end - start), "nanoseconds")


Time taken (Python list): 11267900 nanoseconds


In [7]:
import numpy as np
import time

# Convert the same list to a NumPy array
data = np.array(students)

start = time.perf_counter_ns()

# Vectorized computation
totals_np = data.sum(axis=1)
averages_np = data.mean(axis=1)

end = time.perf_counter_ns()
print("Time taken (NumPy):", round(end - start), "nanoseconds")


Time taken (NumPy): 1335600 nanoseconds


## Axis = 0 vs Axis = 1

In [8]:
import numpy as np
arr = np.array([
    [1, 2, 3],     
    [4, 5, 6],     
    [7, 8, 9]      
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(np.sum(arr, axis=0)) 	#Column-wise stats

[12 15 18]


In [3]:
print(np.sum(arr, axis=1)) #Row-wise stats

[ 6 15 24]
